name: Beyond Gender Manifesto

plugins:
  - jekyll-git_metadata

kramdown:
  parse_block_html: true
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  style: compressed
